---
title: "GSE74548"
author: "hcy_meth meta-analysis group"
date: "21/07/2020"
output:
  html_document:
    toc: true
theme: cosmo
---

##  Introduction

In this report, I will take you through a re-analysis methylation data first described by 
[Kok et al (2015)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4644301/).

In their study, they analysed the DNA methylation patterns of 87 participants of aged 65-75 years with midly elevated Homocysteine levels. THese individuals were randomly asigned to take 400 μg folic acid and 500 μg vitamin B12 per day or a placebo during an intervention period of 2 years.

The platform used in the study is the Illumina Infinium HumanMethylation450k BeadChip assay.
The authors used a pipeline based on DMRs 
([Peters et al, 2017](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4429355/)), together with Benjamini-Hochberg(BH) procedure ([Benjamini et al, 1995](https://rss.onlinelibrary.wiley.com/doi/abs/10.1111/j.2517-6161.1995.tb02031.x)).

The methylation data have been deposited to NCBI GEO repository accession number 
[GSE74548](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE74548)

The main conclusions from the original study were:

* Long-term supplementation with folic acid and vitamin B12 resulted in DNA methylation changes in leukocytes of older persons. 

* A change in DNA methylation was observed to be different between the participants receiving folic acid and vitamin B12 versus placebo.

* DNA methylation levels of several genomic loci were found to correlate to serum levels of either folate, vitamin B12, or plasma homocysteine. 

* Most prominent DNA methylation patterns associated with supplemental intake or status of B-vitamins are related to developmental processes as well as carcinogenesis.

The aim of this work is to;

1. develop the analytical pipelines required for efficient re-analysis of 450K array data,

2. to confirm that we are able to obtain differential methylation results that are similar
to those obtained in the original study, and

3. to critically evaluate the conclusions made in the original study. 










